[package]
name = "quicklime-client"
version = "0.1.0"
authors = ["coderbot <coderbot16@gmail.com>"]

[dependencies]
serde = "^1.0"
serde_json = "^1.0"
serde_derive = "^1.0"
glutin = "0.8"
gfx = "0.15.1"
gfx_window_glutin = "0.16.0"
memmap = "0.5.2"
image = "0.13.0"
num = "0.1"